apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-kubes-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: aws/kubes-secrets
        objectType: secretsmanager
        objectAlias: kubes-secrets
  secretObjects:
    - secretName: kubes-secrets
      type: Opaque
      data:
        - objectName: kubes-secrets
          key: APP_SECRETS

---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-kubes-secrets
type: Opaque
stringData:
  APP_SECRET_PROVIDER: aws_secretsmanager
