apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-eks-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "k8s-secret"
        objectType: "secretsmanager"