apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-k8s-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: aws/k8s-secrets
        objectType: secretsmanager
        objectAlias: k8s-secrets
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: k8s-secrets
          key: APP_SECRETS
