apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-k8s-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: aws/k8s-secrets
        objectType: secretsmanager
        objectAlias: k8s-secrets
  secretObjects:
    - secretName: k8s-secrets
      type: Opaque
      data:
        - objectName: k8s-secrets
          key: APP_SECRETS

---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-k8s-secrets
type: Opaque
stringData:
  APP_SECRET_PROVIDER: aws_secretsmanager
# stringData:
#   Accepts plain text values.
#   Kubernetes automatically encodes them into Base64 when storing the Secret.
#   Makes it easier to define secrets without manually encoding them.
# data:
#   Requires values to be Base64-encoded.
#   When retrieving the secret, Kubernetes decodes it back into plain text.
